import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { CONFIGS } from '../runner.mjs';

// Contract-only acceptance tests. The baseline was serialized from the unmodified
// runner before either registry module existed; it is NOT generated by expansion.
const fixtureRoot = new URL('./fixtures/models/', import.meta.url);
const registryFile = new URL('../models/registry.json', import.meta.url);
const json = url => JSON.parse(readFileSync(url, 'utf8'));
const fixture = name => json(new URL(name, fixtureRoot));
const api = () => import('../models/registry.mjs');
const baseline = json(new URL('./fixtures/runner-configs-2026-09-30.json', import.meta.url));
const expectedRunner = structuredClone(baseline);
const sol61Names = ['sol61-low', 'sol61-medium', 'sol61-high', 'sol61-xhigh', 'sol61-max'];
for (const name of sol61Names) delete expectedRunner[name].capabilityOnly;
const familyNames = ['terra', 'luna', 'astra', 'sol', 'sol6', 'sol61', 'luna6',
  'deepseek-flash', 'opus', 'opus55', 'sonnet5', 'haiku45', 'sonnet55'];

// Literal oracle deliberately disagrees with both alphabetic and numeric sorting.
const orderedExpansion = {
  'z-priced-high': { backend: 'codex', model: 'gpt-5.6-luna', effort: 'high' },
  'z-priced-low': { backend: 'codex', model: 'gpt-5.6-luna', effort: 'low' },
  'deepseek-flash-max': { backend: 'codex', model: 'deepseek-v4-flash', effort: 'max', provider: 'deepseek' },
  'deepseek-flash-none': { backend: 'codex', model: 'deepseek-v4-flash', effort: 'none', provider: 'deepseek' },
  'a-capable-high': { backend: 'claude', model: 'claude-sonnet-5', effort: 'high', provider: 'fixture-provider', capabilityOnly: true },
  haiku45: { backend: 'claude', model: 'claude-haiku-4-5', effort: null, capabilityOnly: true },
};

// Onboarding rule (2026-09-30, kit runbook): new families are APPENDED to the registry. The 59 baseline configs must
// stay an exact ordered prefix of every expansion; anything after them must come from a family added after the
// baseline date, so a new model needs no fixture edit while a removed or altered baseline entry still fails.
const BASELINE_DATE = '2026-09-30';
function baselineHead(configs) {
  const names = Object.keys(configs).slice(0, Object.keys(expectedRunner).length);
  return Object.fromEntries(names.map(name => [name, configs[name]]));
}
function assertPostBaselineTail(configs, registry) {
  const tail = Object.keys(configs).slice(Object.keys(expectedRunner).length);
  const later = registry.families.slice(familyNames.length);
  for (const entry of later) assert.ok(String(entry.added) > BASELINE_DATE, `${entry.family}: appended family must be added after ${BASELINE_DATE}`);
  const allowed = new Set(later.flatMap(entry => entry.efforts.map(effort => effort === null ? entry.configName : `${entry.family}-${effort}`)));
  for (const name of tail) assert.ok(allowed.has(name), `${name}: config after the baseline must belong to an appended family`);
}

function assertOrdered(actual, expected) {
  assert.equal(Object.getPrototypeOf(actual), Object.prototype, 'expansion returns a plain object');
  assert.deepEqual(Object.keys(actual), Object.keys(expected), 'config order and complete identities');
  for (const name of Object.keys(expected)) {
    assert.deepEqual(Object.keys(actual[name]), Object.keys(expected[name]), `${name}: field order and absent keys`);
    assert.deepEqual(actual[name], expected[name], `${name}: exact values`);
    assert.equal(Object.hasOwn(actual[name], 'capabilityOnly'), Object.hasOwn(expected[name], 'capabilityOnly'), `${name}: absent is not false`);
  }
  assert.deepEqual(actual, expected);
}

const invalidCases = [
  ['rule-1-duplicate-family.json', /probe|family/i],
  ['rule-2-config-collision.json', /probe|alias|config.?name/i],
  ['rule-3-efforts.json', /probe|efforts/i],
  ['rule-4-config-name.json', /probe|config.?name|efforts/i],
  ['rule-5-pricing-kind.json', /probe|pricing|kind|reason|input|output/i],
  ['rule-6-credit-rate.json', /probe|input|cachedInput|output/i],
  ['rule-7-backend.json', /probe|backend/i],
  ['rule-8-envelope.json', /formatVersion|families/i],
];

function repaired(rule, bad) {
  const good = structuredClone(bad);
  const first = good.families[0];
  switch (rule) {
    case 1: good.families[1].family = 'other'; break;
    case 2: good.families[1].configName = 'alias'; break;
    case 3: first.efforts = ['high']; break;
    case 4: first.configName = 'probe'; break;
    case 5: delete first.pricing.reason; break;
    case 6: first.pricing.cachedInput = 0.5; break;
    case 7: first.backend = 'codex'; break;
    case 8: good.formatVersion = 1; break;
  }
  return good;
}

// Every alternative below changes only the named rule in a repaired valid fixture.
// Shared disk fixtures also run through loadRegistry, not just validateRegistry.
function variants(rule, good) {
  const cases = [];
  const add = (label, change) => {
    const value = structuredClone(good);
    change(value, value.families[0]);
    cases.push([label, value]);
  };
  if (rule === 3) {
    add('missing efforts', (_r, f) => { delete f.efforts; });
    add('duplicate efforts', (_r, f) => { f.efforts = ['high', 'low', 'high']; });
    add('non-list efforts', (_r, f) => { f.efforts = 'high'; });
    add('non-string effort', (_r, f) => { f.efforts = [7]; });
    add('mixed null and string', (_r, f) => { f.efforts = [null, 'high']; });
  }
  if (rule === 4) add('configName with non-null efforts', (_r, f) => { f.efforts = ['high']; });
  if (rule === 5) {
    add('missing pricing', (_r, f) => { delete f.pricing; });
    add('unknown pricing kind', (_r, f) => { f.pricing = { kind: 'unknown' }; });
    add('capability plus rate', (_r, f) => { f.pricing = { kind: 'capabilityOnly', reason: 'fixture', input: 5 }; });
    add('unpriced plus rate', (_r, f) => { f.pricing = { kind: 'unpriced', output: 30 }; });
    add('unpriced plus capability', (_r, f) => { f.pricing = { kind: 'unpriced', reason: 'fixture' }; });
  }
  if (rule === 6) {
    for (const field of ['input', 'cachedInput', 'output']) {
      add(`${field} missing`, (_r, f) => { delete f.pricing[field]; });
      for (const value of ['5', null, false, [], {}]) {
        add(`${field}=${JSON.stringify(value)}`, (_r, f) => { f.pricing[field] = value; });
      }
    }
  }
  if (rule === 7) {
    for (const backend of ['', 'Codex', null]) add(`backend=${backend}`, (_r, f) => { f.backend = backend; });
  }
  if (rule === 8) {
    add('missing families', r => { delete r.families; });
    for (const value of [{}, null, 'families']) add('non-array families', r => { r.families = value; });
    add('missing formatVersion', r => { delete r.formatVersion; });
    for (const value of [0, '1', null, true]) add(`formatVersion=${value}`, r => { r.formatVersion = value; });
  }
  return cases;
}

test('runner CONFIGS preserves the complete ordered baseline except five absent sol61 flags', () => {
  assert.equal(Object.keys(baseline).length, 59, 'baseline provenance guard, not the compatibility oracle');
  for (const name of sol61Names) {
    assert.equal(baseline[name].capabilityOnly, true);
    assert.equal(Object.hasOwn(CONFIGS[name], 'capabilityOnly'), false, `${name}: remove the key, do not set false`);
  }
  assertOrdered(baselineHead(CONFIGS), expectedRunner);
  assertPostBaselineTail(CONFIGS, json(registryFile));
});

test('default loader retains every family and field, and expansion equals runner and baseline', async () => {
  const { loadRegistry, validateRegistry, expandConfigs } = await api();
  const registry = loadRegistry();
  assert.deepEqual(registry, json(registryFile), 'loading must not discard metadata or provider');
  assert.equal(validateRegistry(registry), undefined);
  assert.deepEqual(registry.families.slice(0, familyNames.length).map(f => f.family), familyNames, 'sonnet5 cannot disappear behind a count check');
  assertOrdered(baselineHead(expandConfigs(registry)), expectedRunner);
  assertPostBaselineTail(expandConfigs(registry), registry);
  assertOrdered(CONFIGS, expandConfigs(registry));
});

test('explicit loader round-trips valid data and does not substitute its default registry', async () => {
  const { loadRegistry, expandConfigs } = await api();
  const file = fileURLToPath(new URL('valid-order.json', fixtureRoot));
  const expected = fixture('valid-order.json');
  assert.deepEqual(loadRegistry(file), expected);
  assertOrdered(expandConfigs(loadRegistry(file)), orderedExpansion);
  assert.deepEqual(loadRegistry(file), expected);
});

test('expansion preserves null, providers, effort order and exact ordered optional fields', async () => {
  const { validateRegistry, expandConfigs } = await api();
  const registry = fixture('valid-order.json');
  assert.equal(validateRegistry(registry), undefined, 'zero and fractional numeric rates are valid');
  assertOrdered(expandConfigs(registry), orderedExpansion);
  assertOrdered(expandConfigs(registry), orderedExpansion);
});

test('expansion follows input sequence under deterministic family and effort permutations', async () => {
  const { expandConfigs } = await api();
  const groups = [['z-priced-high', 'z-priced-low'], ['deepseek-flash-max', 'deepseek-flash-none'], ['a-capable-high'], ['haiku45']];
  for (const permutation of [[3, 2, 1, 0], [1, 3, 0, 2]]) {
    const registry = fixture('valid-order.json');
    registry.families = permutation.map(i => registry.families[i]);
    for (const family of registry.families) family.efforts.reverse();
    const names = permutation.flatMap(i => [...groups[i]].reverse());
    const expected = Object.fromEntries(names.map(name => [name, orderedExpansion[name]]));
    assertOrdered(expandConfigs(registry), expected);
  }
});

test('empty family list is a valid zero-config boundary, not a default-registry fallback', async () => {
  const { validateRegistry, expandConfigs } = await api();
  const registry = { formatVersion: 1, families: [] };
  assert.equal(validateRegistry(registry), undefined);
  assertOrdered(expandConfigs(registry), {});
});

test('all credit families match every rate row; Claude is capability-only and DeepSeek unpriced', async () => {
  const { loadRegistry, expandConfigs } = await api();
  const registry = loadRegistry();
  // Latest dated table: a newly priced family must arrive with a new dated table (runbook step 1.2).
  const tableDir = new URL('../../rounds/round3-2026-09-07/evidence/', import.meta.url);
  const latest = readdirSync(tableDir).filter(name => /^quota-rate-table-.*\.json$/.test(name)).sort().at(-1);
  const rates = json(new URL(latest, tableDir)).families;
  const creditFamilies = registry.families.filter(f => f.pricing.kind === 'credits');
  assert.deepEqual(creditFamilies.map(f => f.family).sort(), Object.keys(rates).sort(), 'nonvacuous price coverage');
  for (const family of creditFamilies) {
    for (const field of ['input', 'cachedInput', 'output']) assert.equal(family.pricing[field], rates[family.family][field], `${family.family}.${field}`);
    assert.equal(typeof family.pricing.source, 'string');
    assert.equal(typeof family.pricing.fetched, 'string');
  }
  const claude = registry.families.filter(f => f.backend === 'claude' && familyNames.includes(f.family));
  assert.deepEqual(claude.map(f => f.family), ['opus', 'opus55', 'sonnet5', 'haiku45', 'sonnet55']);
  for (const family of claude) {
    assert.equal(family.pricing.kind, 'capabilityOnly', family.family);
    assert.equal(typeof family.pricing.reason, 'string');
  }
  const deepseek = registry.families.find(f => f.family === 'deepseek-flash');
  assert.equal(deepseek.pricing.kind, 'unpriced');
  assert.equal(deepseek.provider, 'deepseek');
  assertOrdered(baselineHead(expandConfigs(registry)), expectedRunner);
  assertPostBaselineTail(expandConfigs(registry), registry);
});

test('family lookup distinguishes overlapping prefixes, hyphen boundaries and exact singleton names', async () => {
  const { familyOf, loadRegistry } = await api();
  const registry = loadRegistry();
  for (const [name, family] of [['sol-high', 'sol'], ['sol6-high', 'sol6'], ['sol61-high', 'sol61'], ['haiku45', 'haiku45'], ['deepseek-flash-high', 'deepseek-flash']]) {
    assert.deepEqual(familyOf(name, registry), registry.families.find(f => f.family === family), name);
  }
  for (const name of ['', 'unknown-high', 'sol', 'sol610-high', 'sol6x-high', 'solstice-high', 'haiku450', 'haiku45extra']) assert.equal(familyOf(name, registry), null, name);
  const custom = fixture('valid-order.json');
  custom.families[3].configName = 'custom-singleton';
  assert.deepEqual(familyOf('custom-singleton', custom), custom.families[3]);
  assert.equal(familyOf('custom-singleton-extra', custom), null);
  assert.equal(familyOf('sol-high', { formatVersion: 1, families: [] }), null);
});

for (const [index, [name, message]] of invalidCases.entries()) {
  test(`validation rule ${index + 1}: ${name}; direct validation and explicit-path loader reject`, async () => {
    const { loadRegistry, validateRegistry } = await api();
    const bad = fixture(name);
    const good = repaired(index + 1, bad);
    assert.equal(validateRegistry(good), undefined, 'repairing only the named defect must produce a valid control');
    assert.throws(() => validateRegistry(bad), message, 'dedicated fixture rejected with family/field context');
    assert.throws(() => loadRegistry(fileURLToPath(new URL(name, fixtureRoot))), message, 'loader must actually validate disk data');
    for (const [label, value] of variants(index + 1, good)) assert.throws(() => validateRegistry(value), message, label);
    assert.equal(validateRegistry(good), undefined, 'a failed validation must not poison the next valid call');
  });
}
